# Generated by Django 3.2 on 2023-06-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='jenis_kelamin',
            field=models.CharField(choices=[['L', 'Laki-Laki'], ['P', 'Perempuan']], max_length=1),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='jenis_kelamin',
            field=models.CharField(choices=[['L', 'Laki-Laki'], ['P', 'Perempuan']], max_length=1),
        ),
    ]
