# Generated by Django 3.2 on 2023-06-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_auto_20230603_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelajaran',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pelajaran',
            name='siswa',
            field=models.ManyToManyField(related_name='pelajaran', to='akademik.Siswa'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[['A', 'Aktif'], ['N', 'Tidak Aktif']], default='N', max_length=15),
        ),
    ]
