# Generated by Django 3.2 on 2023-06-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_remove_siswa_guru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guru',
            options={'verbose_name': 'Guru', 'verbose_name_plural': 'Guru'},
        ),
        migrations.AlterModelOptions(
            name='pelajaran',
            options={'verbose_name': 'Pelajaran', 'verbose_name_plural': 'Pelajaran'},
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name': 'Siswa', 'verbose_name_plural': 'Siswa'},
        ),
    ]
